# Generated by Django 4.2.4 on 2024-02-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=250)),
                ('employee_name', models.TextField()),
                ('employee_phone', models.IntegerField()),
            ],
        ),
    ]
